// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MessageBackground","status":true,"description":"(v.2.0) Displays an image behind messages in place of the windowskin","parameters":{"Image Variable ID":"1","Disable Switch ID":"1"}}
];
